apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - imageName: my.repo.com/my-service
      workspace: .
      bazel:
        target: //services/my-service:image.tar
  local: {}
deploy:
  helm:
    releases:
      - name: my-service
        chartPath: helm/my-service
        valuesFilePath: helm/my-service/values.yaml
        values:
          image.imageName: my.repo.com/my-service
