# Note: We use a local version of bazel-javascript rules here.
#
# You should remove this and use the remote version below instead.
local_repository(
  name = "bazel_javascript",
  path = "../..",
)

# git_repository(
#     name = "bazel_javascript",
#     remote = "https://github.com/zenclabs/bazel-javascript.git",
#     tag = <use the latest tag>,
# )

git_repository(
    name = "build_bazel_rules_nodejs",
    remote = "https://github.com/bazelbuild/rules_nodejs.git",
    tag = "0.14.2",
)

# Required by build_bazel_rules_nodejs.
git_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib.git",
    tag = "0.5.0",
)

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")

node_repositories(
    package_json = [],
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "5d64414477ffe87b16e248986c0731aee821ea3d626121cfeeec4ef7096812ca",
    strip_prefix = "rules_docker-0.5.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.5.0.tar.gz"],
)

# Import bazel_source ourselves, to work around checksum issues
# https://github.com/bazelbuild/rules_docker/issues/500
http_archive(
    name = "bazel_source",
    sha256 = "46dfffac884ccd51fcb493dd86463cb8c21be949fdb17634ca37805fd544beae",
    urls = [("https://releases.bazel.build/0.17.0/rc1/bazel-0.17.0rc1-dist.zip")],
)

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
    container_repositories = "repositories",
)

container_repositories()

container_pull(
    name = "node_alpine_image",
    registry = "index.docker.io",
    repository = "library/node",
    tag = "8.11.3-alpine",
)
