# Note: We use a local version of bazel-javascript rules here.
#
# You should remove this and use the remote version below instead.
local_repository(
    name = "bazel_javascript",
    path = "../..",
)

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
# git_repository(
#     name = "bazel_javascript",
#     remote = "https://github.com/zenclabs/bazel-javascript.git",
#     tag = <use the latest tag>,
# )

git_repository(
    name = "build_bazel_rules_nodejs",
    remote = "https://github.com/bazelbuild/rules_nodejs.git",
    tag = "0.15.0",
)

load("@build_bazel_rules_nodejs//:package.bzl", "rules_nodejs_dependencies")

rules_nodejs_dependencies()

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")

node_repositories(
    package_json = [],
)
