package(default_visibility = ["//visibility:public"])

load("@bazel_node//:defs.bzl", "npm_binary")

npm_binary(
  name = "cli",
  install = "//tests/npm-binary:packages",
  binary = "getstorybook",
)
