# If you choose to copy this example, make sure to use the git_repository()
# rules below instead.
local_repository(
  name = "bazel_typescript",
  path = "../..",
)

local_repository(
  name = "bazel_node",
  path = "../../../bazel-node",
)

# git_repository(
#   name = "bazel_typescript",
#   remote = "https://github.com/zenclabs/bazel-typescript.git",
#   tag = "0.0.21", # check for the latest tag when you install
# )

# git_repository(
#   name = "bazel_node",
#   remote = "https://github.com/zenclabs/bazel-node.git",
#   tag = "0.0.11", # check for the latest tag when you install
# )
