# If you choose to copy this example, make sure to use the git_repository()
# rule below instead.
local_repository(
  name = "bazel_typescript",
  path = "../..",
)

# git_repository(
#   name = "bazel_typescript",
#   remote = "https://github.com/zenclabs/bazel-typescript.git",
#   tag = "0.0.18", # check for the latest tag when you install
# )

git_repository(
  name = "bazel_node",
  remote = "https://github.com/zenclabs/bazel-node.git",
  tag = "0.0.8", # check for the latest tag when you install
)
