git_repository(
  name = "bazel_typescript",
  remote = "https://github.com/zenclabs/bazel-typescript.git",
  tag = "0.0.7", # check for the latest tag when you install
)

git_repository(
  name = "bazel_node",
  remote = "https://github.com/zenclabs/bazel-node.git",
  tag = "0.0.8", # check for the latest tag when you install
)
